"""empty message

Revision ID: 0970eab581ea
Revises: 577c6f6db013
Create Date: 2019-05-25 16:59:48.998929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0970eab581ea'
down_revision = '577c6f6db013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('alarm_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_record', 'alarm_time')
    # ### end Alembic commands ###
