"""empty message

Revision ID: 1b10b218b215
Revises: 488e1a1ddc38
Create Date: 2020-05-07 02:02:13.853374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b10b218b215'
down_revision = '488e1a1ddc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ip', table_name='equipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ip', 'equipment', ['ip'], unique=True)
    # ### end Alembic commands ###
