"""empty message

Revision ID: 1e4134f9b0bf
Revises: 
Create Date: 2019-05-20 11:02:06.168876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4134f9b0bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.Column('contact_tel', sa.String(length=15), nullable=True),
    sa.Column('parent_id', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('gaode_longitude', sa.Float(), nullable=True),
    sa.Column('gaode_latitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('use_department', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('SIM_id', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('group',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_record',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_record',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('operator_id', sa.String(length=30), nullable=True),
    sa.Column('deal_describe', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_group_relationship',
    sa.Column('group_id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'equipment_id')
    )
    op.create_table('equipment_report_log',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_report_log')
    op.drop_table('equipment_group_relationship')
    op.drop_table('alarm_record')
    op.drop_table('user_record')
    op.drop_table('group')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
