"""empty message

Revision ID: 1ed942f06342
Revises: 0970eab581ea
Create Date: 2019-05-25 17:03:27.908216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ed942f06342'
down_revision = '0970eab581ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alarm_record', 'alarm_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('equipment_report_log', sa.Column('report_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_report_log', 'report_time')
    op.alter_column('alarm_record', 'alarm_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
