"""empty message

Revision ID: 21845751b341
Revises: 7e1aafc73879
Create Date: 2019-05-26 13:14:08.408481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21845751b341'
down_revision = '7e1aafc73879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('create_user', sa.String(length=30), nullable=False))
    op.add_column('role', sa.Column('remarks', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'remarks')
    op.drop_column('role', 'create_user')
    # ### end Alembic commands ###
