"""empty message

Revision ID: 3627ad0e479d
Revises: f24cda3d3505
Create Date: 2020-05-05 20:52:55.803902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3627ad0e479d'
down_revision = 'f24cda3d3505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_record',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('record_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_record')
    # ### end Alembic commands ###
