"""empty message

Revision ID: 3df81592d3ba
Revises: 1b10b218b215
Create Date: 2020-06-04 16:37:25.046598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df81592d3ba'
down_revision = '1b10b218b215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('heartbeat_interval', sa.Integer(), nullable=True, comment='单位秒'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'heartbeat_interval')
    # ### end Alembic commands ###
