"""empty message

Revision ID: 40ad5a5aab65
Revises: cc9362f914c8
Create Date: 2019-05-26 17:20:57.334651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ad5a5aab65'
down_revision = 'cc9362f914c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('position_city', sa.String(length=20), nullable=True))
    op.add_column('equipment', sa.Column('position_district', sa.String(length=20), nullable=True))
    op.add_column('equipment', sa.Column('position_province', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'position_province')
    op.drop_column('equipment', 'position_district')
    op.drop_column('equipment', 'position_city')
    # ### end Alembic commands ###
