"""empty message

Revision ID: 488e1a1ddc38
Revises: 3627ad0e479d
Create Date: 2020-05-06 00:57:42.431673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488e1a1ddc38'
down_revision = '3627ad0e479d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_record', sa.Column('data', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_record', 'data')
    # ### end Alembic commands ###
