"""empty message

Revision ID: 4fdc6802b290
Revises: 40ad5a5aab65
Create Date: 2019-05-26 17:37:07.775024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdc6802b290'
down_revision = '40ad5a5aab65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gov', sa.Column('city', sa.String(length=20), nullable=True))
    op.add_column('gov', sa.Column('district', sa.String(length=20), nullable=True))
    op.add_column('gov', sa.Column('level', sa.Integer, nullable=True))
    op.add_column('gov', sa.Column('province', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gov', 'province')
    op.drop_column('gov', 'level')
    op.drop_column('gov', 'district')
    op.drop_column('gov', 'city')
    # ### end Alembic commands ###
