"""empty message

Revision ID: 577c6f6db013
Revises: ef65aa90c62f
Create Date: 2019-05-24 21:14:37.294927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577c6f6db013'
down_revision = 'ef65aa90c62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('if_Administrative', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'if_Administrative')
    # ### end Alembic commands ###
