"""empty message

Revision ID: 74dfbc37a188
Revises: 7efa2834281e
Create Date: 2019-05-28 19:12:28.424338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74dfbc37a188'
down_revision = '7efa2834281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('live', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'live')
    # ### end Alembic commands ###
