"""empty message

Revision ID: 7561241e0c33
Revises: 783ed8455aef
Create Date: 2020-06-05 17:38:43.165305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7561241e0c33'
down_revision = '783ed8455aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ui_report_log', sa.Column('CphaseActivePower', sa.Float(), nullable=False, comment='C相有功功率'))
    op.drop_column('ui_report_log', 'CphaseActivePpwer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ui_report_log', sa.Column('CphaseActivePpwer', mysql.FLOAT(), nullable=False, comment='C相有功功率'))
    op.drop_column('ui_report_log', 'CphaseActivePower')
    # ### end Alembic commands ###
