"""empty message

Revision ID: 7d5d7bd4ac73
Revises: 8e6e899b42da
Create Date: 2019-05-26 00:04:53.800679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5d7bd4ac73'
down_revision = '8e6e899b42da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('gaode_latitude', sa.Float(precision=15, asdecimal=10), nullable=True))
    op.add_column('equipment', sa.Column('gaode_longitude', sa.Float(precision=15, asdecimal=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'gaode_longitude')
    op.drop_column('equipment', 'gaode_latitude')
    # ### end Alembic commands ###
