"""empty message

Revision ID: 7e1aafc73879
Revises: a95e35e76fc0
Create Date: 2019-05-26 00:08:26.377935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1aafc73879'
down_revision = 'a95e35e76fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('gaode_latitude', sa.Float(precision='15,8'), nullable=True))
    op.add_column('equipment', sa.Column('gaode_longitude', sa.Float(precision='15,8'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'gaode_longitude')
    op.drop_column('equipment', 'gaode_latitude')
    # ### end Alembic commands ###
