"""empty message

Revision ID: 7efa2834281e
Revises: 4fdc6802b290
Create Date: 2019-05-28 14:06:05.315776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efa2834281e'
down_revision = '4fdc6802b290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('if_drop_child', sa.BOOLEAN(), nullable=False))
    op.add_column('role', sa.Column('if_drop_equipment', sa.BOOLEAN(), nullable=False))
    op.add_column('user', sa.Column('live', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'live')
    op.drop_column('role', 'if_drop_equipment')
    op.drop_column('role', 'if_drop_child')
    # ### end Alembic commands ###
