"""empty message

Revision ID: 8e6e899b42da
Revises: bf68938ef052
Create Date: 2019-05-26 00:04:31.150177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e6e899b42da'
down_revision = 'bf68938ef052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'gaode_latitude')
    op.drop_column('equipment', 'gaode_longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('gaode_longitude', mysql.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('gaode_latitude', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
