"""empty message

Revision ID: a95e35e76fc0
Revises: 7d5d7bd4ac73
Create Date: 2019-05-26 00:07:38.007524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a95e35e76fc0'
down_revision = '7d5d7bd4ac73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'gaode_longitude')
    op.drop_column('equipment', 'gaode_latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('gaode_latitude', mysql.FLOAT(), nullable=True))
    op.add_column('equipment', sa.Column('gaode_longitude', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
