"""empty message

Revision ID: cc9362f914c8
Revises: 21845751b341
Create Date: 2019-05-26 16:14:05.947187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9362f914c8'
down_revision = '21845751b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gov',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('gaode_center_longitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('gaode_center_latitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.Column('contact_tel', sa.String(length=15), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gov')
    # ### end Alembic commands ###
