"""empty message

Revision ID: e5a2494c66e0
Revises: fc8c97f9fe63
Create Date: 2019-05-31 21:10:46.216689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a2494c66e0'
down_revision = 'fc8c97f9fe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('describe', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_record', 'describe')
    # ### end Alembic commands ###
