"""empty message

Revision ID: ed8f3e3aafbd
Revises: 
Create Date: 2019-05-31 19:33:45.242904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8f3e3aafbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gov',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('gaode_center_longitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('gaode_center_latitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.Column('contact_tel', sa.String(length=15), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('create_user', sa.String(length=30), nullable=False),
    sa.Column('if_role', sa.BOOLEAN(), nullable=False),
    sa.Column('if_add_equipment', sa.BOOLEAN(), nullable=False),
    sa.Column('if_modify_equipment', sa.BOOLEAN(), nullable=False),
    sa.Column('if_drop_equipment', sa.BOOLEAN(), nullable=False),
    sa.Column('if_add_child', sa.BOOLEAN(), nullable=False),
    sa.Column('if_modify_child', sa.BOOLEAN(), nullable=False),
    sa.Column('if_drop_child', sa.BOOLEAN(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.Column('contact_tel', sa.String(length=15), nullable=True),
    sa.Column('live', sa.BOOLEAN(), nullable=False),
    sa.Column('parent_id', sa.String(length=30), nullable=True),
    sa.Column('role_id', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('class_', sa.String(length=20), nullable=False),
    sa.Column('gaode_longitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('gaode_latitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('use_department', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.Column('live', sa.BOOLEAN(), nullable=False),
    sa.Column('position_province', sa.String(length=20), nullable=True),
    sa.Column('position_city', sa.String(length=20), nullable=True),
    sa.Column('position_district', sa.String(length=20), nullable=True),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('SIM_id', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('group',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_record',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_record',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('operator_id', sa.String(length=30), nullable=True),
    sa.Column('deal_describe', sa.String(length=50), nullable=True),
    sa.Column('alarm_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_group_relationship',
    sa.Column('group_id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'equipment_id')
    )
    op.create_table('equipment_report_log',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('report_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_report_log')
    op.drop_table('equipment_group_relationship')
    op.drop_table('alarm_record')
    op.drop_table('user_record')
    op.drop_table('group')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('gov')
    # ### end Alembic commands ###
