"""empty message

Revision ID: ef65aa90c62f
Revises: f168f23847da
Create Date: 2019-05-23 22:47:40.712268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef65aa90c62f'
down_revision = 'f168f23847da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('if_role', sa.BOOLEAN(), nullable=False),
    sa.Column('if_add_equipment', sa.BOOLEAN(), nullable=False),
    sa.Column('if_modify_equipment', sa.BOOLEAN(), nullable=False),
    sa.Column('if_add_child', sa.BOOLEAN(), nullable=False),
    sa.Column('if_modify_child', sa.BOOLEAN(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role_id', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_table('role')
    # ### end Alembic commands ###
