"""empty message

Revision ID: f168f23847da
Revises: 1e4134f9b0bf
Create Date: 2019-05-20 13:19:05.260376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f168f23847da'
down_revision = '1e4134f9b0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('class_', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'class_')
    # ### end Alembic commands ###
