"""empty message

Revision ID: f24cda3d3505
Revises: 60b3755933c5
Create Date: 2020-01-09 21:07:12.004750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f24cda3d3505'
down_revision = '60b3755933c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_report_log')
    op.add_column('alarm_record', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('alarm_record', 'deal_describe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm_record', sa.Column('deal_describe', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('alarm_record', 'end_time')
    op.create_table('equipment_report_log',
    sa.Column('id', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('equipment_id', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('class_', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('report_time', mysql.DATETIME(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('modify_time', mysql.DATETIME(), nullable=True),
    sa.Column('describe', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='equipment_report_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
