"""empty message

Revision ID: f28a25b94594
Revises: 
Create Date: 2019-05-31 19:15:07.894819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28a25b94594'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('class_', sa.String(length=20), nullable=False),
    sa.Column('gaode_longitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('gaode_latitude', sa.Float(precision='15,8'), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=24), nullable=True),
    sa.Column('use_department', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.Column('live', sa.BOOLEAN(), nullable=False),
    sa.Column('position_province', sa.String(length=20), nullable=True),
    sa.Column('position_city', sa.String(length=20), nullable=True),
    sa.Column('position_district', sa.String(length=20), nullable=True),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('SIM_id', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('group',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_record',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('operator_id', sa.String(length=30), nullable=True),
    sa.Column('deal_describe', sa.String(length=50), nullable=True),
    sa.Column('alarm_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_group_relationship',
    sa.Column('group_id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'equipment_id')
    )
    op.create_table('equipment_report_log',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=30), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=False),
    sa.Column('report_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_report_log')
    op.drop_table('equipment_group_relationship')
    op.drop_table('alarm_record')
    op.drop_table('group')
    op.drop_table('equipment')
    # ### end Alembic commands ###
